### ISSUE TITLE
[FEATURE] Landscape file as JSON

### ISSUE THREAD

**Issue by whvneo** [baloise/orchestra-maven-plugin#3]
**Is your feature request related to a problem? Please describe.**
As an enduser the format for complex variables described in an INI file is not very clear. Also I got some problems without indent the VALUE line and using lowercase for VALUE.

**Describe the solution you'd like**
I would like to have the JSON format for the landscape file. It should be possible to use objects and arrays in this JSON-File.
The file should end with the suffix json.

It may be possible to use one file per target environment or one for all environments (filename the should be landscape.json)

 e.g.
```
{
    "prod": {
        "ee_openhr": {
            "host": "myserver.example.com",
            "port": "443"
        },
        "ee_mailto": [
            "receiver1@example.com",
            "second_receiver@example.com",
        ]
    }
}
``` 

**Describe alternatives you've considered**
No alternatives found

**Additional context**
It should read pretty printed JSON files and one liner the same way

**Comment by culmat** [comment]
doc see https://baloise.github.io/orchestra-maven-plugin/scenario-deploy-mojo.html#landscapeFile
